### ISSUE TITLE
Contact Form - The form should not be accepted if an invalid email address is used.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Sarnia-Anti-Aging-Clinic#12]

**Comment by tgascoigne14** [comment]
It let me submit the form with only using 'test' there should be an @ in the address or it will not be accepted.

If a user does not enter an @ in the address they should not be able to move on.

**Comment by hemantcci** [comment]
Can you try one more time because in mine it's not going forward when email is wrong.

**Comment by tgascoigne14** [comment]
That worked - thank you

_Tina Gascoigne_
_Account Lead_
CCI Studios, Inc.
_Mail:_ 136 Christina St. N., Sarnia, ON N7T 5T9
_Phone:_ (519) 337-8837
_Fax:_ (519) 337-8316
_Email:_ tgascoigne@ccistudios.com
_Web:_ www.ccistudios.com

**2010, 2012 & 2013 Outstanding Business Achievement Award Recipient**

P _Please print this e-mail only if necessary_

 _You have received this email because you have a business relationship
with CCI Studios.  If you believe this was done in error or if you would
like to unsubscribe from any future digital communication, please click
here http://www.ccistudios.com/unsubscribe._
