### ISSUE TITLE
Services - Forever Young - Some before and after images are not the consistently sized.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Sarnia-Anti-Aging-Clinic#3]
![fc2dfdd6-f7f0-11e4-806b-d79d63a0fa84](https://cloud.githubusercontent.com/assets/8631079/7587370/bdc264b8-f883-11e4-8b83-47e4722a0580.png)

**Comment by hemantcci** [comment]
Hey Tina I have tried keeping them same size but some images are originally like this .
